#!/bin/bash
# 本地源码安装说明脚本（与 npm 发布模式保持一致）

set -euo pipefail

echo "spec-first 本地源码安装已切换为 npm CLI 模型。"
echo ""
echo "推荐安装："
echo "  npm install -g spec-first"
echo ""
echo "项目初始化："
echo "  spec-first doctor"
echo "  spec-first init --claude"
echo ""
echo "Stage-0 入口说明："
echo "  /spec:bootstrap        默认稳定入口"
echo "  /spec:graph-bootstrap  图引导 Phase 0-4 入口（阶段2最小闭环）"
echo ""
echo "如果你之前安装过 pnpm 版本或旧的全局 shim，先重开一个终端或执行："
echo "  hash -r"
echo "再运行上面的命令，避免 shell 缓存继续指向旧路径。"
echo ""
echo "如果要验证源码安装，可参考本地 tarball 安装流程："
echo "  1. npm pack"
echo "  2. npm install -g ./spec-first-<version>.tgz"
echo "  3. 在目标项目执行 spec-first doctor"
echo "  4. 在目标项目执行 spec-first init --claude"
echo "  5. 检查 .claude/commands/spec/ 和 .claude/skills/"
echo "  6. 确认 /spec:bootstrap 仍是默认入口，/spec:graph-bootstrap 可生成阶段2闭环产物"
echo ""
echo "当前仓库不再尝试把自己注册为 Claude plugin。"
