'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { runDoctor } = require('../../src/cli/commands/doctor');
const { runInit } = require('../../src/cli/commands/init');

function makeTempDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'spec-first-doctor-runtime-tools-'));
}

function withCwd(cwd, fn) {
  const previous = process.cwd();
  process.chdir(cwd);
  try {
    return fn();
  } finally {
    process.chdir(previous);
  }
}

function captureCommand(cwd, runner, args) {
  const logs = [];
  const errors = [];
  const originalLog = console.log;
  const originalError = console.error;
  console.log = (message = '') => logs.push(String(message));
  console.error = (message = '') => errors.push(String(message));
  try {
    const exitCode = withCwd(cwd, () => runner(args));
    return {
      exitCode,
      stdout: logs.join('\n'),
      stderr: errors.join('\n'),
    };
  } finally {
    console.log = originalLog;
    console.error = originalError;
  }
}

function writeExecutable(filePath, contents) {
  fs.writeFileSync(filePath, contents, 'utf8');
  fs.chmodSync(filePath, 0o755);
}

function withEnv(updates, fn) {
  const previous = {};
  for (const [key, value] of Object.entries(updates)) {
    previous[key] = process.env[key];
    if (value === undefined) {
      delete process.env[key];
    } else {
      process.env[key] = value;
    }
  }

  try {
    return fn();
  } finally {
    for (const [key, value] of Object.entries(previous)) {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    }
  }
}

describe('doctor runtime tools boundary', () => {
  test('help explains JSON status fields and setup/bootstrap boundaries', () => {
    const projectRoot = makeTempDir();

    try {
      const result = captureCommand(projectRoot, runDoctor, ['--help']);

      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain('install_health: Node/Git/package-level checks for running the CLI.');
      expect(result.stdout).toContain('runtime_asset_health: managed Claude/Codex runtime assets generated by spec-first init.');
      expect(result.stdout).toContain('workflow_runnability: verified | simulated | not_verified.');
      expect(result.stdout).toContain('verification_evidence_stale');
      expect(result.stdout).toContain('MCP/helper setup is handled by $spec-mcp-setup or /spec:mcp-setup.');
      expect(result.stdout).toContain('Graph/provider readiness is compiled by $spec-graph-bootstrap or /spec:graph-bootstrap.');
    } finally {
      fs.rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test('does not require a global runtime tools block after init', () => {
    const projectRoot = makeTempDir();
    const initLogSpy = jest.spyOn(console, 'log').mockImplementation(() => {});

    try {
      expect(withCwd(projectRoot, () => runInit(['--codex', '-u', 'reviewer', '--lang', 'zh']))).toBe(0);
      const agents = fs.readFileSync(path.join(projectRoot, 'AGENTS.md'), 'utf8');
      expect(agents).not.toContain('spec-first:runtime-tools:start');

      const result = captureCommand(projectRoot, runDoctor, ['--codex', '--json']);
      const payload = JSON.parse(result.stdout);
      const platformChecks = payload.platform_checks.codex;
      const checkNames = platformChecks.map((check) => check.name);
      const checkText = platformChecks
        .map((check) => [check.name, check.message, check.fix].filter(Boolean).join('\n'))
        .join('\n');

      expect(result.exitCode).toBe(0);
      expect(checkNames).not.toContain('AGENTS.md runtime tools index');
      expect(checkText).not.toContain('managed runtime-tools block');
    } finally {
      initLogSpy.mockRestore();
      fs.rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test('bounds git and host CLI version checks with a timeout', () => {
    const projectRoot = makeTempDir();
    const fakeBin = path.join(projectRoot, 'bin');
    fs.mkdirSync(fakeBin, { recursive: true });
    writeExecutable(path.join(fakeBin, 'git'), '#!/bin/sh\nsleep 5\n');
    writeExecutable(path.join(fakeBin, 'codex'), '#!/bin/sh\nsleep 5\n');

    const initLogSpy = jest.spyOn(console, 'log').mockImplementation(() => {});

    try {
      expect(withCwd(projectRoot, () => runInit(['--codex', '-u', 'reviewer', '--lang', 'zh']))).toBe(0);
      const result = withEnv({
        PATH: `${fakeBin}${path.delimiter}${process.env.PATH || ''}`,
        SPEC_FIRST_EXTERNAL_COMMAND_TIMEOUT_MS: '50',
      }, () => {
        expect(process.env.PATH.split(path.delimiter)[0]).toBe(fakeBin);
        expect(fs.existsSync(path.join(fakeBin, 'git'))).toBe(true);
        return captureCommand(projectRoot, runDoctor, ['--codex', '--json']);
      });
      const payload = JSON.parse(result.stdout);
      const gitCheck = payload.common_checks.find((check) => check.name === 'Git');
      const codexCheck = payload.platform_checks.codex.find((check) => check.name === 'Codex');

      expect(gitCheck).toMatchObject({
        level: 'ERROR',
        message: 'version check timed out',
      });
      expect(codexCheck).toMatchObject({
        level: 'WARNING',
        message: 'version check timed out',
      });
      expect(result.exitCode).toBe(1);
    } finally {
      initLogSpy.mockRestore();
      fs.rmSync(projectRoot, { recursive: true, force: true });
    }
  });
});
