'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const REPO_ROOT = path.join(__dirname, '..', '..');
const PACKAGE_JSON_PATH = path.join(REPO_ROOT, 'package.json');
const PACKAGE_LOCK_PATH = path.join(REPO_ROOT, 'package-lock.json');
const NPM_IGNORE_PATH = path.join(REPO_ROOT, '.npmignore');
const POSTINSTALL_PATH = path.join(REPO_ROOT, 'bin/postinstall.js');
const TYPECHECK_SCRIPT_PATH = path.join(REPO_ROOT, 'scripts/typecheck-js.js');
const README_PATH = path.join(REPO_ROOT, 'README.md');

function removeDirectoryIfEmpty(dirPath) {
  try {
    fs.rmdirSync(dirPath);
  } catch (error) {
    if (!error || (error.code !== 'ENOENT' && error.code !== 'ENOTEMPTY')) {
      throw error;
    }
  }
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

describe('package install contracts', () => {
  test('retired graph native packages are absent from package manifests', () => {
    const pkg = readJson(PACKAGE_JSON_PATH);
    const lock = readJson(PACKAGE_LOCK_PATH);
    const sqliteDep = 'better' + '-sqlite3';
    const parserDep = 'tree' + '-sitter';
    const nativePackages = [
      sqliteDep,
      parserDep,
      `${parserDep}-c`,
      `${parserDep}-c-sharp`,
      `${parserDep}-cpp`,
      `${parserDep}-go`,
      `${parserDep}-java`,
      `${parserDep}-javascript`,
      `${parserDep}-kotlin`,
      `${parserDep}-objc`,
      `${parserDep}-php`,
      `${parserDep}-python`,
      `${parserDep}-ruby`,
      `${parserDep}-rust`,
      `${parserDep}-scala`,
      `${parserDep}-swift`,
      `${parserDep}-typescript`,
    ];

    for (const packageName of nativePackages) {
      expect(pkg.dependencies[packageName]).toBeUndefined();
      expect(pkg.optionalDependencies?.[packageName]).toBeUndefined();
      expect(lock.packages[''].dependencies[packageName]).toBeUndefined();
      expect(lock.packages[''].optionalDependencies?.[packageName]).toBeUndefined();
      expect(lock.packages[`node_modules/${packageName}`]).toBeUndefined();
    }

    expect(pkg.files).not.toContain('vendor/');
    expect(pkg.files).toContain('docs/contracts/verifiers/');
    expect(pkg.files).toContain('scripts/generate-runtime-capability-catalog.js');
    expect(pkg.files).toContain('scripts/typecheck-js.js');
    expect(pkg.files).toContain('!skills/**/__pycache__/**');
    expect(pkg.files).toContain('!skills/**/*.pyc');
    expect(pkg.files).toContain('!skills/**/*.pyo');
    expect(pkg.scripts['test:e2e:' + 'crg']).toBeUndefined();
    expect(pkg.scripts.test).not.toContain('test:e2e:' + 'crg');
    expect(pkg.overrides).toBeUndefined();
  });

  test('package ignore excludes generated Python bytecode caches', () => {
    const npmIgnore = fs.readFileSync(NPM_IGNORE_PATH, 'utf8');

    expect(npmIgnore).toContain('__pycache__/');
    expect(npmIgnore).toContain('*.pyc');
    expect(npmIgnore).toContain('*.pyo');
  });

  test('published README uses absolute repository links instead of bundling docs payload', () => {
    const pkg = readJson(PACKAGE_JSON_PATH);
    const readme = fs.readFileSync(README_PATH, 'utf8');

    expect(pkg.files).toContain('README.md');
    expect(pkg.files).not.toContain('README.zh-CN.md');
    expect(pkg.files).not.toContain('docs/assets/readme/');
    expect(pkg.files).not.toContain('docs/05-用户手册/');
    expect(readme).toContain('https://raw.githubusercontent.com/sunrain520/spec-first/main/docs/assets/readme/spec-first-flow.svg');
    expect(readme).toContain('https://github.com/sunrain520/spec-first/blob/main/README.zh-CN.md');
    expect(readme).toContain('https://github.com/sunrain520/spec-first/blob/main/docs/05-%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/README.md');
    expect(readme).not.toMatch(/\]\(\.\/|\]\(\.\.\//);
    expect(readme).not.toMatch(/!\[[^\]]*\]\(\.\/|!\[[^\]]*\]\(\.\.\//);
  });

  test('npm pack dry-run excludes generated Python bytecode caches', () => {
    const cacheDir = path.join(REPO_ROOT, 'skills/spec-release-notes/scripts/__pycache__');
    const bytecodePath = path.join(cacheDir, `pack-contract-${process.pid}-${Date.now()}.cpython-311.pyc`);
    const npmCacheDir = fs.mkdtempSync(path.join(os.tmpdir(), 'spec-first-npm-pack-'));

    fs.mkdirSync(cacheDir, { recursive: true });
    fs.writeFileSync(bytecodePath, 'generated bytecode fixture', 'utf8');

    try {
      const result = spawnSync('npm', ['pack', '--dry-run', '--json'], {
        cwd: REPO_ROOT,
        encoding: 'utf8',
        env: {
          ...process.env,
          npm_config_cache: npmCacheDir,
        },
      });

      expect(result.status).toBe(0);
      const [packResult] = JSON.parse(result.stdout);
      const packedPaths = packResult.files.map((file) => file.path);
      const bytecodePaths = packedPaths.filter((filePath) => (
        filePath.includes('/__pycache__/') || /\.py[co]$/.test(filePath)
      ));

      expect(bytecodePaths).toEqual([]);
    } finally {
      fs.rmSync(bytecodePath, { force: true });
      fs.rmSync(npmCacheDir, { recursive: true, force: true });
      removeDirectoryIfEmpty(cacheDir);
    }
  });

  test('postinstall keeps setup summary without native repair logic', () => {
    const postinstall = fs.readFileSync(POSTINSTALL_PATH, 'utf8');
    const sqliteDep = 'better' + '-sqlite3';
    const parserDep = 'tree' + '-sitter';
    const pruneScript = 'prune' + '-native';
    const prebuildTool = 'prebuild' + '-install';

    expect(postinstall).not.toMatch(new RegExp(`CRG|${sqliteDep}|${parserDep}|${pruneScript}|npm rebuild|${prebuildTool}`, 'i'));
    expect(postinstall).toMatch(/spec-first init/);
    expect(postinstall).toMatch(/managed assets/);
    expect(postinstall).toMatch(/Claude|Codex/);
  });

  test('typecheck script covers packaged cli source directories', () => {
    const pkg = readJson(PACKAGE_JSON_PATH);
    const typecheckSource = fs.readFileSync(TYPECHECK_SCRIPT_PATH, 'utf8');

    expect(pkg.scripts.typecheck).toBe('node scripts/typecheck-js.js');
    expect(typecheckSource).toContain("const CHECK_ROOTS = ['bin', 'src', 'scripts']");
    expect(typecheckSource).toContain("new Set(['.cjs', '.js'])");

    const result = spawnSync(process.execPath, [TYPECHECK_SCRIPT_PATH], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    });

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('typecheck passed');
  });
});
