'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ClaudeAdapter = require('../../src/cli/adapters/claude');
const CodexAdapter = require('../../src/cli/adapters/codex');
const { inspectInstalledAssets, syncSkills } = require('../../src/cli/plugin');

const REPO_ROOT = path.join(__dirname, '..', '..');
const SKILL_PATH = path.join(REPO_ROOT, 'skills', 'using-spec-first', 'SKILL.md');
const GOVERNANCE_PATH = path.join(
  REPO_ROOT,
  'src',
  'cli',
  'contracts',
  'dual-host-governance',
  'skills-governance.json',
);

function read(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

describe('using-spec-first contracts', () => {
  test('source skill defines the entry-governor contract', () => {
    const skill = read(SKILL_PATH);

    expect(skill).toContain('name: using-spec-first');
    expect(skill).toContain('what spec-first workflow or command to run next');
    expect(skill).toContain('standalone meta skill and entry governor');
    expect(skill).toContain('not a command-backed workflow');
    expect(skill).toContain('Source Of Truth And Runtime Surface');
    expect(skill).toContain('The managed bootstrap blocks in `CLAUDE.md` and `AGENTS.md` are intentionally thin startup reminders');
    expect(skill).toContain('generated by `spec-first init --claude` or `spec-first init --codex`');
    expect(skill).toContain('Repair stale or missing runtime guidance with `spec-first init --claude` or `spec-first init --codex`');
    expect(skill).toContain('If You Are Already In A Workflow');
    expect(skill).toContain('If You Are A Subagent');
    expect(skill).not.toContain('generated by `spec-first init --codex` or `spec-first init --codex`');
    expect(skill).not.toContain('with `spec-first init --codex` or `spec-first init --codex`');
    expect(skill).toContain('Decision Output Contract');
    expect(skill).toContain('User Next-Step Guide Mode');
    expect(skill).toContain('when the user explicitly asks what to run next');
    expect(skill).toContain('which `spec-first` command to use');
    expect(skill).toContain('This mode is read-only.');
    expect(skill).toContain('must not create brainstorm, plan, task, review, solution, or runtime artifacts');
    expect(skill).toContain('Output exactly one best next entrypoint, one concrete reason, and one next action');
    expect(skill).toContain('Do not print the full workflow menu.');
    expect(skill).toContain('Use a compact, user-visible shape so the answer is easy to scan');
    expect(skill).toContain('推荐入口: <current-host entrypoint>');
    expect(skill).toContain('理由: <one concrete reason>');
    expect(skill).toContain('下一步: <one action the user can take now>');
    expect(skill).toContain('Recommended entrypoint');
    expect(skill).toContain('reply `继续` to run it now');
    expect(skill).toContain('If the user asks only for guidance about the next step, use User Next-Step Guide Mode');
    expect(skill).toContain('Use the Routing Priority and Routing Rules below as the source of truth');
    expect(skill).toContain('Use the exact current-host public entrypoint those rules select');
    expect(skill).toContain('Do not start the selected workflow from guide mode unless the user explicitly asks to continue with that workflow.');
    expect(skill).toContain('Low-confidence cases need one narrow confirmation before routing');
    expect(skill).toContain('a change could be either a bug fix or a product behavior change');
    expect(skill).toContain('If a brainstorm requirements document exists and implementation direction is not yet planned, recommend plan.');
    expect(skill).toContain('If there is an existing diff and the user asks whether it is ready, recommend code review or doc review based on the artifact.');
    expect(skill).toContain('After init, prefer setup/readiness guidance when runtime or MCP readiness is unresolved');
    expect(skill).toContain('substantial work');
    expect(skill).toContain('Spec-First Self-Work');
    expect(skill).toContain('docs/10-prompt/结构化项目角色契约.md');
    expect(skill).toContain('host instruction blocks');
    expect(skill).toContain('If the request asks for review plus concrete revisions, route to work and keep a review posture during execution.');
    expect(skill).toContain('For source changes, update source-of-truth files, the narrowest contract tests, and `CHANGELOG.md`');
    expect(skill).toContain('Do not modify generated `.claude/`, `.codex/`, or `.agents/skills/` mirrors');
    expect(skill).toContain('environment setup, host setup, MCP setup, missing tools, or host readiness');
    expect(skill).toContain('project-local setup');
    expect(skill).toContain('Parent Workspace Graph Evidence');
    expect(skill).toContain('workspace-graph-targets.v1');
    expect(skill).toContain('GitNexus-first evidence');
    expect(skill).toContain('bounded candidate repos');
    expect(skill).toContain('degraded-fallback');
    expect(skill).toContain('explicit `target_repo` / per-child scope');
    expect(skill).toContain('/spec:' + 'graph' + '-bootstrap');
    expect(skill).toContain('$spec-' + 'graph' + '-bootstrap');
    expect(skill).toContain('/spec:standards');
    expect(skill).toContain('$spec-standards');
    expect(skill).not.toContain('/spec:setup');
    expect(skill).not.toContain('$spec-setup');
    expect(skill).not.toContain('spec-first ' + 'crg');
    expect(skill).toContain('workflow-first');
    expect(skill).toContain('Explicit Route Normalization');
    expect(skill).toContain("If the user names the other host's equivalent public workflow, translate it to the current host entrypoint");
    expect(skill).toContain('Codex should translate `/spec:work` to `$spec-work`');
    expect(skill).toContain('Do not invent a `/spec:*` or `$spec-*` command for standalone skills');
    expect(skill).toContain('Workflow-Owned Dispatch Admission');
    expect(skill).toContain('an explicit invocation of the current host public workflow entrypoint counts as the user\'s explicit request for that bounded workflow-owned subagent work');
    expect(skill).toContain('do not require a second phrase such as "use subagents" or "parallel agents"');
    expect(skill).toContain('This applies only to the workflow\'s documented read-only reviewer/researcher phase');
    expect(skill).toContain('$spec-doc-review` multi-persona document reviewers');
    expect(skill).toContain('It does not authorize unrelated helper agents, hidden workflows, startup reminder agents, mutating worker dispatch, or beta delegation paths');
    expect(skill).toContain('follow that workflow\'s documented fallback instead of dispatching');
    expect(skill).toContain('Routing Priority');
    expect(skill).toContain('Explicit user route');
    expect(skill).toContain('Optimization routes');
    expect(skill).toContain('Routing Red Flags');
    expect(skill).toContain('Do not chain multiple workflows automatically');
    expect(skill).toContain('Do not route by keyword alone');
    expect(skill).toContain('It does **not** exist to force every task through brainstorming.');
    expect(skill).toContain('Do **not** make `spec-brainstorm` the universal default front door.');
    expect(skill).toContain('Do **not** adopt the `using-superpowers` rule');
    expect(skill).toContain('Do **not** write Codex entrypoints as `/spec:*`.');
    expect(skill).toContain('Do **not** write Claude workflow entrypoints as `$spec-*`.');
    expect(skill).toContain('Claude workflow entrypoints use `/spec:*`');
    expect(skill).toContain('Codex workflow entrypoints use `$spec-*`');
    expect(skill).toContain('$spec-doc-review` means the default multi-persona document-review workflow');
    expect(skill).toContain('Codex Startup Version Reminder Boundary');
    expect(skill).toContain('not a verified deterministic SessionStart hook');
    expect(skill).toContain('top-level Codex orchestrator');
    expect(skill).toContain('spec-first startup-reminder --codex');
    expect(skill).toContain('Missing CLI, command failure, network failure, empty output, or malformed local state must be ignored');
    expect(skill).toContain('The reminder points to `$spec-update`');
    expect(skill).toContain('Bounded subagents, leaf reviewers, and worker agents must not run the startup reminder');
    expect(skill).toContain('do not reload or invoke `using-spec-first` just to bootstrap yourself');
    expect(skill).toContain('`using-spec-first` governs **entry routing only**');
    expect(skill).toContain('Artifact And Evidence Boundaries');
    expect(skill).toContain('This skill should not ask the agent to fabricate command results');
    expect(skill).toContain('Do not use this governor to create pseudo-plan, pseudo-task, or pseudo-review artifacts.');
    expect(skill).toContain('Do **not** expose internal-only skills as user entrypoints.');
    expect(skill).toContain('legacy/internal `lfg`');
    expect(skill).toContain('spec-session-inventory');
    expect(skill).toContain('using-spec-first` itself is a standalone meta skill');
    expect(skill).toContain('/spec:update');
    expect(skill).toContain('$spec-update');
    expect(skill).toContain('/spec:doc-review');
    expect(skill).toContain('$spec-doc-review');
    expect(skill).toContain('git-commit-push-pr');
    expect(skill).toContain('description-only mode');
    expect(skill).not.toContain('/spec:pr-description');
    expect(skill).not.toContain('$spec-pr-description');
    expect(skill).toContain('/spec:optimize');
    expect(skill).toContain('$spec-optimize');
    expect(skill).toContain('/spec:plan');
    expect(skill).toContain('$spec-plan');
    expect(skill).toContain('spec-write-tasks');
    expect(skill).toContain('not a `/spec:*` or `$spec-*` workflow entrypoint');
    expect(skill).toContain('/spec:work');
    expect(skill).toContain('$spec-work');
    expect(skill).toContain('Do not recommend this route in User Next-Step Guide Mode unless the current request explicitly asks for beta execution');
    expect(skill).toContain('Ordinary execution-ready work routes to the stable work entrypoint.');
    expect(skill).toContain('Legacy/internal `lfg` must not be recommended as a public workflow path.');
    expect(skill).not.toContain('/spec:next');
    expect(skill).not.toContain('$spec-next');
    expect(skill).not.toContain('/spec:guide');
    expect(skill).not.toContain('$spec-guide');
  });

  test('skills governance exposes using-spec-first as a standalone meta skill on both hosts', () => {
    const governance = JSON.parse(read(GOVERNANCE_PATH));

    expect(governance.skills).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          skill_name: 'using-spec-first',
          entry_surface: 'standalone_skill',
          command_name: null,
          host_scope: 'dual_host',
          owner_host: null,
          host_delivery: {
            claude: 'skill',
            codex: 'skill',
          },
        }),
      ]),
    );
  });

  test('runtime transforms preserve internal guidance text when transformed directly', () => {
    const sourceSkill = read(SKILL_PATH);
    const claude = new ClaudeAdapter();
    const codex = new CodexAdapter();
    const claudeRuntime = claude.transformSkillContent(sourceSkill);
    const codexRuntime = codex.transformSkillContent(sourceSkill, { skillName: 'using-spec-first' });

    expect(claudeRuntime).toContain('name: using-spec-first');
    expect(codexRuntime).toContain('name: using-spec-first');
    expect(claudeRuntime).toContain('Claude workflow entrypoints use `/spec:*`');
    expect(codexRuntime).toContain('Codex workflow entrypoints use `$spec-*`');
    expect(codexRuntime).toContain('spec-first startup-reminder --codex');
    expect(codexRuntime).toContain('Workflow-Owned Dispatch Admission');
    expect(codexRuntime).toContain('explicit request for that bounded workflow-owned subagent work');
    expect(codexRuntime).toContain('$spec-doc-review` means the default multi-persona document-review workflow');
    expect(codexRuntime).toContain('generated by `spec-first init --claude` or `spec-first init --codex`');
    expect(codexRuntime).toContain('Repair stale or missing runtime guidance with `spec-first init --claude` or `spec-first init --codex`');
    expect(codexRuntime).not.toContain('generated by `spec-first init --codex` or `spec-first init --codex`');
    expect(codexRuntime).not.toContain('with `spec-first init --codex` or `spec-first init --codex`');
    expect(codexRuntime).toContain('Bounded subagents, leaf reviewers, and worker agents must not run the startup reminder');
    expect(codexRuntime).toContain('using-spec-first` itself is a standalone meta skill');
    expect(claudeRuntime).toContain('User Next-Step Guide Mode');
    expect(codexRuntime).toContain('User Next-Step Guide Mode');
    expect(claudeRuntime).toContain('Output exactly one best next entrypoint, one concrete reason, and one next action');
    expect(claudeRuntime).toContain('推荐入口: <current-host entrypoint>');
    expect(codexRuntime).toContain('Next action');
    expect(codexRuntime).toContain('This mode is read-only.');
    expect(claudeRuntime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
    expect(claudeRuntime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
    expect(codexRuntime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
    expect(codexRuntime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
  });

  test('codex runtime install notes do not trigger path rewrite drift', () => {
    const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'using-spec-first-codex-runtime-'));
    const codex = new CodexAdapter();

    try {
      syncSkills(projectRoot, codex);
      const status = inspectInstalledAssets(projectRoot, codex).skills;
      const usingSpecFirstDrift = status.drifted.find((entry) => entry.skillName === 'using-spec-first');

      expect(usingSpecFirstDrift).toBeUndefined();
      expect(read(path.join(projectRoot, '.agents', 'skills', 'using-spec-first', 'SKILL.md'))).toContain(
        'Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`',
      );
    } finally {
      fs.rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test('Codex adapter preserves dual-host init guidance while rewriting source runtime paths', () => {
    const codex = new CodexAdapter();
    const rendered = codex.transformSkillContent(
      [
        'Repair with spec-first init --claude or spec-first init --codex.',
        'See `.claude/commands/spec/work.md` for the legacy command path.',
      ].join('\n'),
      {
        skillName: 'using-spec-first',
        isWorkflowSkill: true,
      },
    );

    expect(rendered).toContain('spec-first init --claude or spec-first init --codex');
    expect(rendered).not.toContain('spec-first init --codex or spec-first init --codex');
    expect(rendered).toContain('`.agents/skills/spec-work/SKILL.md`');
  });
});
