'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ClaudeAdapter = require('../../src/cli/adapters/claude');
const CodexAdapter = require('../../src/cli/adapters/codex');
const { inspectInstalledAssets, syncSkills } = require('../../src/cli/plugin');

const REPO_ROOT = path.join(__dirname, '..', '..');
const SKILL_PATH = path.join(REPO_ROOT, 'skills', 'using-spec-first', 'SKILL.md');
const GOVERNANCE_PATH = path.join(
  REPO_ROOT,
  'src',
  'cli',
  'contracts',
  'dual-host-governance',
  'skills-governance.json',
);

function read(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function expectContainsAll(content, snippets) {
  for (const snippet of snippets) {
    expect(content).toContain(snippet);
  }
}

describe('using-spec-first contracts', () => {
  test('source skill defines the entry-governor contract', () => {
    const skill = read(SKILL_PATH);

    expectContainsAll(skill, [
      'name: using-spec-first',
      'what spec-first workflow or command to run next',
      'standalone meta skill and entry governor',
      'not a command-backed workflow',
      'Contract Summary',
      '| When to use |',
      '| When not to use |',
      '| Inputs |',
      '| Outputs |',
      '| Artifacts |',
      '| Failure modes |',
      '| Workflow |',
      '| Downstream consumers |',
      'scripts and CLI commands prepare deterministic facts; the LLM decides the workflow recommendation',
      'Source Of Truth And Runtime Surface',
      'The managed bootstrap blocks in `CLAUDE.md` and `AGENTS.md` are intentionally thin startup reminders',
      'generated by `spec-first init` after choosing the target host',
      'Repair stale or missing runtime guidance with `spec-first init` after choosing the target host',
      'If You Are Already In A Workflow',
      'If You Are A Subagent',
      'Decision Output Contract',
      'User Next-Step Guide Mode',
      'when the user explicitly asks what to run next',
      'which `spec-first` command to use',
      'This mode is read-only.',
      'must not create brainstorm, plan, task, review, solution, or runtime artifacts',
      'Output exactly one best next entrypoint, one concrete reason, and one next action',
      'Do not print the full workflow menu.',
      '推荐入口: <current-host entrypoint>',
      '理由: <one concrete reason>',
      '下一步: <one action the user can take now>',
      'Recommended entrypoint',
      'reply `继续` to run it now',
      'Use the Routing Priority and Routing Rules below as the source of truth',
      'Use the exact current-host public entrypoint those rules select',
      'Low-confidence cases need one narrow confirmation before routing',
      'a change could be either a bug fix or a product behavior change',
      'If a brainstorm requirements document exists and implementation direction is not yet planned, recommend plan.',
      'If there is an existing diff and the user asks whether it is ready, recommend code review or doc review based on the artifact.',
      'After init, prefer setup/readiness guidance only when the user asks about setup/readiness',
      'After init, when runtime or MCP readiness is unresolved but the user has a clear lightweight docs, small-code, plan, work, or review goal',
      'route by that goal and require the selected workflow to disclose degraded setup/MCP evidence when relevant',
      'Spec-First Self-Work',
      'docs/10-prompt/结构化项目角色契约.md',
      'host instruction blocks',
      'If the request asks for review plus concrete revisions, route to work and keep a review posture during execution.',
      'For source changes, update source-of-truth files, the narrowest contract tests, and `CHANGELOG.md`',
      'Do not modify generated `.claude/`, `.codex/`, or `.agents/skills/` mirrors',
      'Parent Workspace Direct Reads',
      'If the user asks a read-only codebase question from a parent workspace containing multiple child Git repos',
      'Use bounded direct reads in the likely child repo candidates and state the target-repo assumption.',
      'explicit `target_repo` / per-child scope',
      'Explicit Route Normalization',
      "If the user names the other host's equivalent public workflow, translate it to the current host entrypoint",
      'Codex should translate `/spec:work` to `$spec-work`',
      'Do not invent a `/spec:*` or `$spec-*` command for standalone skills',
      'Workflow Dispatch Admission',
      'Routing into a public workflow authorizes that workflow to run.',
      'It does not by itself override host-level subagent tool contracts.',
      'call `spawn_agent` only when the current request explicitly asks for subagents, delegated work, parallel agents, persona reviewer dispatch',
      'or when an upstream workflow delegates from an already authorized multi-agent context',
      'Some public workflows prefer multi-persona or research phases when host capability and authorization are both present',
      '$spec-doc-review` multi-persona document reviewers',
      'If the user names `spec-doc-review` in a document-review request without the `$` prefix',
      'normalize it to the current host\'s public document-review entrypoint',
      'Do not invent extra dispatch authorization from normalization',
      'explicit dispatch authorization is absent',
      'follow that workflow\'s documented fallback instead of dispatching',
      'Routing Priority',
      'Optimization routes',
      'Routing Red Flags',
      'Do not chain multiple workflows automatically',
      'Do not route by keyword alone',
      'It does **not** exist to force every task through brainstorming.',
      'Do **not** make `spec-brainstorm` the universal default front door.',
      'Do **not** adopt the `using-superpowers` rule',
      'Do **not** write Codex entrypoints as `/spec:*`.',
      'Do **not** write Claude workflow entrypoints as `$spec-*`.',
      'Claude workflow entrypoints use `/spec:*`',
      'Codex workflow entrypoints use `$spec-*`',
      '$spec-doc-review` means the document-review workflow. It uses bounded reviewer dispatch only when the current request also satisfies Codex `spawn_agent` authorization',
      'Codex Startup Reminder Boundary',
      'not a verified deterministic SessionStart hook',
      'top-level Codex orchestrator',
      'spec-first startup-reminder --codex',
      'Missing CLI, command failure, network failure, empty output, or malformed local state must be ignored',
      'Version reminders point to `$spec-update`',
      'Bounded subagents, leaf reviewers, and worker agents must not run the startup reminder',
      'They inherit the parent task scope.',
      'do not reload or invoke `using-spec-first` just to bootstrap yourself',
      '`using-spec-first` governs **entry routing only**',
      'Artifact And Evidence Boundaries',
      'This skill should not ask the agent to fabricate command results',
      'Do not use this governor to create pseudo-plan, pseudo-task, or pseudo-review artifacts.',
      'Do **not** expose internal-only skills as user entrypoints.',
      'legacy/internal `lfg`',
      '`git-worktree`',
      'using-spec-first` itself is a standalone meta skill',
      '/spec:update',
      '$spec-update',
      '/spec:doc-review',
      '$spec-doc-review',
      '/spec:skill-audit',
      '$spec-skill-audit',
      '/spec:app-consistency-audit',
      '$spec-app-consistency-audit',
      '/spec:prd',
      '$spec-prd',
      'brownfield PRD authoring',
      '/spec:optimize',
      '$spec-optimize',
      '/spec:plan',
      '$spec-plan',
      'spec-write-tasks',
      'not a `/spec:*` or `$spec-*` workflow entrypoint',
      '/spec:work',
      '$spec-work',
      'Ordinary execution-ready work routes to the stable work entrypoint.',
      'Legacy/internal `lfg` must not be recommended as a public workflow path.',
    ]);

    expect(skill).not.toContain('/spec:standards');
    expect(skill).not.toContain('$spec-standards');
    expect(skill).not.toContain('/spec:setup');
    expect(skill).not.toContain('$spec-setup');
    expect(skill).not.toContain('generated by `spec-first init --codex` or `spec-first init --codex`');
    expect(skill).not.toContain('with `spec-first init --codex` or `spec-first init --codex`');
    expect(skill).not.toContain('spec-session-inventory');
    expect(skill).not.toContain('spec-session-extract');
    expect(skill).not.toContain('/spec:pr-description');
    expect(skill).not.toContain('$spec-pr-description');
    expect(skill).not.toContain('/spec:next');
    expect(skill).not.toContain('$spec-next');
    expect(skill).not.toContain('/spec:guide');
    expect(skill).not.toContain('$spec-guide');
  });

  test('skills governance exposes using-spec-first as a standalone meta skill on both hosts', () => {
    const governance = JSON.parse(read(GOVERNANCE_PATH));

    expect(governance.skills).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          skill_name: 'using-spec-first',
          entry_surface: 'standalone_skill',
          command_name: null,
          host_scope: 'dual_host',
          owner_host: null,
          host_delivery: {
            claude: 'skill',
            codex: 'skill',
          },
        }),
      ]),
    );
  });

  test('runtime transforms preserve internal guidance text when transformed directly', () => {
    const sourceSkill = read(SKILL_PATH);
    const claude = new ClaudeAdapter();
    const codex = new CodexAdapter();
    const claudeRuntime = claude.transformSkillContent(sourceSkill);
    const codexRuntime = codex.transformSkillContent(sourceSkill, { skillName: 'using-spec-first' });

    expect(claudeRuntime).toContain('name: using-spec-first');
    expect(codexRuntime).toContain('name: using-spec-first');
    expect(claudeRuntime).toContain('Claude workflow entrypoints use `/spec:*`');
    expect(codexRuntime).toContain('Codex workflow entrypoints use `$spec-*`');
    expect(codexRuntime).toContain('spec-first startup-reminder --codex');
    expect(codexRuntime).not.toContain('query proof after setup');
    expect(codexRuntime).toContain('Workflow Dispatch Admission');
    expect(codexRuntime).toContain('It does not by itself override host-level subagent tool contracts.');
    expect(codexRuntime).toContain('call `spawn_agent` only when the current request explicitly asks for subagents, delegated work, parallel agents, persona reviewer dispatch');
    expect(codexRuntime).toContain('$spec-doc-review` means the document-review workflow. It uses bounded reviewer dispatch only when the current request also satisfies Codex `spawn_agent` authorization');
    expect(codexRuntime).toContain('generated by `spec-first init` after choosing the target host');
    expect(codexRuntime).toContain('Repair stale or missing runtime guidance with `spec-first init` after choosing the target host');
    expect(codexRuntime).not.toContain('generated by `spec-first init --codex` or `spec-first init --codex`');
    expect(codexRuntime).not.toContain('with `spec-first init --codex` or `spec-first init --codex`');
    expect(codexRuntime).toContain('Bounded subagents, leaf reviewers, and worker agents must not run the startup reminder');
    expect(codexRuntime).toContain('using-spec-first` itself is a standalone meta skill');
    expect(claudeRuntime).toContain('User Next-Step Guide Mode');
    expect(codexRuntime).toContain('User Next-Step Guide Mode');
    expect(claudeRuntime).toContain('Output exactly one best next entrypoint, one concrete reason, and one next action');
    expect(claudeRuntime).toContain('推荐入口: <current-host entrypoint>');
    expect(codexRuntime).toContain('Next action');
    expect(codexRuntime).toContain('This mode is read-only.');
    expect(claudeRuntime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
    expect(claudeRuntime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
    expect(codexRuntime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
    expect(codexRuntime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
  });

  test('runtime install notes do not rewrite using-spec-first source-of-truth path', () => {
    const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'using-spec-first-codex-runtime-'));

    try {
      for (const [adapter, runtimePath] of [
        [new ClaudeAdapter(), path.join(projectRoot, '.claude', 'skills', 'using-spec-first', 'SKILL.md')],
        [new CodexAdapter(), path.join(projectRoot, '.agents', 'skills', 'using-spec-first', 'SKILL.md')],
      ]) {
        syncSkills(projectRoot, adapter);
        const status = inspectInstalledAssets(projectRoot, adapter).skills;
        const usingSpecFirstDrift = status.drifted.find((entry) => entry.skillName === 'using-spec-first');
        const runtime = read(runtimePath);

        expect(usingSpecFirstDrift).toBeUndefined();
        expect(runtime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
        expect(runtime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
        expect(runtime).toContain('`skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
        expect(runtime).not.toContain('`.claude/skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
        expect(runtime).not.toContain('`.agents/skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
      }
    } finally {
      fs.rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test('Codex adapter preserves dual-host init guidance while rewriting source runtime paths', () => {
    const codex = new CodexAdapter();
    const rendered = codex.transformSkillContent(
      [
        'Repair with spec-first init and choose the target host.',
        'See `.claude/commands/spec/work.md` for the legacy command path.',
      ].join('\n'),
      {
        skillName: 'using-spec-first',
        isWorkflowSkill: true,
      },
    );

    expect(rendered).toContain('spec-first init and choose the target host');
    expect(rendered).not.toContain('spec-first init --codex or spec-first init --codex');
    expect(rendered).toContain('`.agents/skills/spec-work/SKILL.md`');
  });
});
