'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ClaudeAdapter = require('../../src/cli/adapters/claude');
const CodexAdapter = require('../../src/cli/adapters/codex');
const { inspectInstalledAssets, syncSkills } = require('../../src/cli/plugin');

const REPO_ROOT = path.join(__dirname, '..', '..');
const SKILL_PATH = path.join(REPO_ROOT, 'skills', 'using-spec-first', 'SKILL.md');
const GOVERNANCE_PATH = path.join(
  REPO_ROOT,
  'src',
  'cli',
  'contracts',
  'dual-host-governance',
  'skills-governance.json',
);

function read(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function expectContainsAll(content, snippets) {
  for (const snippet of snippets) {
    expect(content).toContain(snippet);
  }
}

describe('using-spec-first contracts', () => {
  test('source skill defines the entry-governor contract', () => {
    const skill = read(SKILL_PATH);

    expectContainsAll(skill, [
      'name: using-spec-first',
      'what spec-first workflow or command to run next',
      'standalone meta skill and entry governor',
      'not a command-backed workflow',
      'Contract Summary',
      '| When to use |',
      '| When not to use |',
      '| Inputs |',
      '| Outputs |',
      '| Artifacts |',
      '| Failure modes |',
      '| Workflow |',
      '| Downstream consumers |',
      'scripts and CLI commands prepare deterministic facts; the LLM decides the workflow recommendation',
      'Source Of Truth And Runtime Surface',
      'The managed bootstrap blocks in `CLAUDE.md` and `AGENTS.md` are intentionally thin startup reminders',
      'generated by `spec-first init --claude` or `spec-first init --codex`',
      'Repair stale or missing runtime guidance with `spec-first init --claude` or `spec-first init --codex`',
      'If You Are Already In A Workflow',
      'If You Are A Subagent',
      'Decision Output Contract',
      'User Next-Step Guide Mode',
      'when the user explicitly asks what to run next',
      'which `spec-first` command to use',
      'This mode is read-only.',
      'must not create brainstorm, plan, task, review, solution, or runtime artifacts',
      'Output exactly one best next entrypoint, one concrete reason, and one next action',
      'Do not print the full workflow menu.',
      '推荐入口: <current-host entrypoint>',
      '理由: <one concrete reason>',
      '下一步: <one action the user can take now>',
      'Recommended entrypoint',
      'reply `继续` to run it now',
      'Use the Routing Priority and Routing Rules below as the source of truth',
      'Use the exact current-host public entrypoint those rules select',
      'Low-confidence cases need one narrow confirmation before routing',
      'a change could be either a bug fix or a product behavior change',
      'If a brainstorm requirements document exists and implementation direction is not yet planned, recommend plan.',
      'If there is an existing diff and the user asks whether it is ready, recommend code review or doc review based on the artifact.',
      'After init, prefer setup/readiness guidance only when the user asks about setup/readiness',
      'After init, when runtime or MCP readiness is unresolved but the user has a clear lightweight docs, small-code, plan, work, or review goal',
      'route by that goal and require the selected workflow to disclose degraded graph/MCP evidence when relevant',
      'Spec-First Self-Work',
      'docs/10-prompt/结构化项目角色契约.md',
      'host instruction blocks',
      'If the request asks for review plus concrete revisions, route to work and keep a review posture during execution.',
      'For source changes, update source-of-truth files, the narrowest contract tests, and `CHANGELOG.md`',
      'Do not modify generated `.claude/`, `.codex/`, or `.agents/skills/` mirrors',
      'Parent Workspace Graph Evidence',
      'Graph Refresh Routing Boundary',
      'refresh GitNexus',
      'rebuild graph/index',
      'update graph readiness after branch switch',
      'verify current graph impact evidence',
      'route to `$spec-graph-bootstrap` / `/spec:graph-bootstrap` when setup-owned provider projection is already ready',
      'stale provider package projection',
      'Entry routing itself never runs provider analyze/build/status/query commands',
      'never writes canonical `.spec-first/graph/*`, `.spec-first/providers/*`, or `.spec-first/impact/*` artifacts',
      'Branch switch, pull, rebase, merge, dirty worktree changes, and provider fingerprint mismatch',
      'not automatic routing-governor rebuild triggers',
      'workspace-graph-targets.v1',
      'GitNexus-first evidence',
      'bounded candidate repos',
      'degraded-fallback',
      'explicit `target_repo` / per-child scope',
      'Explicit Route Normalization',
      "If the user names the other host's equivalent public workflow, translate it to the current host entrypoint",
      'Codex should translate `/spec:work` to `$spec-work`',
      'Do not invent a `/spec:*` or `$spec-*` command for standalone skills',
      'Workflow-Owned Dispatch Admission',
      'explicit invocation of the current host public workflow entrypoint counts as the user\'s explicit request for that bounded workflow-owned subagent work',
      'do not require a second phrase such as "use subagents" or "parallel agents"',
      'This applies only to the workflow\'s documented read-only reviewer/researcher phase',
      '$spec-doc-review` multi-persona document reviewers',
      'It does not authorize unrelated helper agents, hidden workflows, startup reminder agents, mutating worker dispatch, or beta delegation paths',
      'If the user names `spec-doc-review` in a document-review request without the `$` prefix',
      'normalize it to the current host\'s public document-review entrypoint',
      'Do not treat a missing extra "use subagents" phrase as a request for single-agent report-only',
      'follow that workflow\'s documented fallback instead of dispatching',
      'Routing Priority',
      'Optimization routes',
      'Routing Red Flags',
      'Do not chain multiple workflows automatically',
      'Do not route by keyword alone',
      'It does **not** exist to force every task through brainstorming.',
      'Do **not** make `spec-brainstorm` the universal default front door.',
      'Do **not** adopt the `using-superpowers` rule',
      'Do **not** write Codex entrypoints as `/spec:*`.',
      'Do **not** write Claude workflow entrypoints as `$spec-*`.',
      'Claude workflow entrypoints use `/spec:*`',
      'Codex workflow entrypoints use `$spec-*`',
      '$spec-doc-review` means the default multi-persona document-review workflow',
      'Codex Startup Version Reminder Boundary',
      'not a verified deterministic SessionStart hook',
      'top-level Codex orchestrator',
      'spec-first startup-reminder --codex',
      'Missing CLI, command failure, network failure, empty output, or malformed local state must be ignored',
      'The reminder points to `$spec-update`',
      'Bounded subagents, leaf reviewers, and worker agents must not run the startup reminder',
      'do not reload or invoke `using-spec-first` just to bootstrap yourself',
      '`using-spec-first` governs **entry routing only**',
      'Artifact And Evidence Boundaries',
      'This skill should not ask the agent to fabricate command results',
      'Do not use this governor to create pseudo-plan, pseudo-task, or pseudo-review artifacts.',
      'Do **not** expose internal-only skills as user entrypoints.',
      'legacy/internal `lfg`',
      '`git-worktree`',
      'using-spec-first` itself is a standalone meta skill',
      '/spec:update',
      '$spec-update',
      'compile or refresh GitNexus graph readiness, provider index, or graph-provider query proof after setup',
      '/spec:doc-review',
      '$spec-doc-review',
      'git-commit-push-pr',
      'description-only mode',
      '/spec:optimize',
      '$spec-optimize',
      '/spec:plan',
      '$spec-plan',
      'spec-write-tasks',
      'not a `/spec:*` or `$spec-*` workflow entrypoint',
      '/spec:work',
      '$spec-work',
      'Ordinary execution-ready work routes to the stable work entrypoint.',
      'Legacy/internal `lfg` must not be recommended as a public workflow path.',
      'workspace-gitnexus-readiness.v1',
      'group.status="group-ready"',
      'bounded registry/per-repo fallback or explicit disclosure, not provider failure',
    ]);

    expect(skill).toContain('/spec:' + 'graph' + '-bootstrap');
    expect(skill).toContain('$spec-' + 'graph' + '-bootstrap');
    expect(skill).not.toContain('/spec:' + 'standards');
    expect(skill).not.toContain('$spec-' + 'standards');
    expect(skill).not.toContain('/spec:setup');
    expect(skill).not.toContain('$spec-setup');
    expect(skill).not.toContain('spec-first ' + 'crg');
    expect(skill).not.toContain('generated by `spec-first init --codex` or `spec-first init --codex`');
    expect(skill).not.toContain('with `spec-first init --codex` or `spec-first init --codex`');
    expect(skill).not.toContain('spec-session-inventory');
    expect(skill).not.toContain('spec-session-extract');
    expect(skill).not.toContain('/spec:pr-description');
    expect(skill).not.toContain('$spec-pr-description');
    expect(skill).not.toContain('/spec:next');
    expect(skill).not.toContain('$spec-next');
    expect(skill).not.toContain('/spec:guide');
    expect(skill).not.toContain('$spec-guide');
  });

  test('skills governance exposes using-spec-first as a standalone meta skill on both hosts', () => {
    const governance = JSON.parse(read(GOVERNANCE_PATH));

    expect(governance.skills).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          skill_name: 'using-spec-first',
          entry_surface: 'standalone_skill',
          command_name: null,
          host_scope: 'dual_host',
          owner_host: null,
          host_delivery: {
            claude: 'skill',
            codex: 'skill',
          },
        }),
      ]),
    );
  });

  test('runtime transforms preserve internal guidance text when transformed directly', () => {
    const sourceSkill = read(SKILL_PATH);
    const claude = new ClaudeAdapter();
    const codex = new CodexAdapter();
    const claudeRuntime = claude.transformSkillContent(sourceSkill);
    const codexRuntime = codex.transformSkillContent(sourceSkill, { skillName: 'using-spec-first' });

    expect(claudeRuntime).toContain('name: using-spec-first');
    expect(codexRuntime).toContain('name: using-spec-first');
    expect(claudeRuntime).toContain('Claude workflow entrypoints use `/spec:*`');
    expect(codexRuntime).toContain('Codex workflow entrypoints use `$spec-*`');
    expect(codexRuntime).toContain('spec-first startup-reminder --codex');
    expect(codexRuntime).toContain('Workflow-Owned Dispatch Admission');
    expect(codexRuntime).toContain('explicit request for that bounded workflow-owned subagent work');
    expect(codexRuntime).toContain('$spec-doc-review` means the default multi-persona document-review workflow');
    expect(codexRuntime).toContain('Do not treat a missing extra "use subagents" phrase as a request for single-agent report-only');
    expect(codexRuntime).toContain('generated by `spec-first init --claude` or `spec-first init --codex`');
    expect(codexRuntime).toContain('Repair stale or missing runtime guidance with `spec-first init --claude` or `spec-first init --codex`');
    expect(codexRuntime).not.toContain('generated by `spec-first init --codex` or `spec-first init --codex`');
    expect(codexRuntime).not.toContain('with `spec-first init --codex` or `spec-first init --codex`');
    expect(codexRuntime).toContain('Bounded subagents, leaf reviewers, and worker agents must not run the startup reminder');
    expect(codexRuntime).toContain('using-spec-first` itself is a standalone meta skill');
    expect(claudeRuntime).toContain('User Next-Step Guide Mode');
    expect(codexRuntime).toContain('User Next-Step Guide Mode');
    expect(claudeRuntime).toContain('Output exactly one best next entrypoint, one concrete reason, and one next action');
    expect(claudeRuntime).toContain('推荐入口: <current-host entrypoint>');
    expect(codexRuntime).toContain('Next action');
    expect(codexRuntime).toContain('This mode is read-only.');
    expect(claudeRuntime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
    expect(claudeRuntime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
    expect(codexRuntime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
    expect(codexRuntime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
  });

  test('runtime install notes do not rewrite using-spec-first source-of-truth path', () => {
    const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'using-spec-first-codex-runtime-'));

    try {
      for (const [adapter, runtimePath] of [
        [new ClaudeAdapter(), path.join(projectRoot, '.claude', 'skills', 'using-spec-first', 'SKILL.md')],
        [new CodexAdapter(), path.join(projectRoot, '.agents', 'skills', 'using-spec-first', 'SKILL.md')],
      ]) {
        syncSkills(projectRoot, adapter);
        const status = inspectInstalledAssets(projectRoot, adapter).skills;
        const usingSpecFirstDrift = status.drifted.find((entry) => entry.skillName === 'using-spec-first');
        const runtime = read(runtimePath);

        expect(usingSpecFirstDrift).toBeUndefined();
        expect(runtime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
        expect(runtime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
        expect(runtime).toContain('`skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
        expect(runtime).not.toContain('`.claude/skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
        expect(runtime).not.toContain('`.agents/skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
      }
    } finally {
      fs.rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test('Codex adapter preserves dual-host init guidance while rewriting source runtime paths', () => {
    const codex = new CodexAdapter();
    const rendered = codex.transformSkillContent(
      [
        'Repair with spec-first init --claude or spec-first init --codex.',
        'See `.claude/commands/spec/work.md` for the legacy command path.',
      ].join('\n'),
      {
        skillName: 'using-spec-first',
        isWorkflowSkill: true,
      },
    );

    expect(rendered).toContain('spec-first init --claude or spec-first init --codex');
    expect(rendered).not.toContain('spec-first init --codex or spec-first init --codex');
    expect(rendered).toContain('`.agents/skills/spec-work/SKILL.md`');
  });
});
